<a href="https://colab.research.google.com/github/erinijapranckeviciene/MF54609_18981_1_20241/blob/main/QP/QP_textprocessing_with_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text processing with RNN using IMDB reviews dataset.

#### Run cells and answer following questions.

## Question 1:

#### The dense model below was built using 1 Ngram model and classification accuracy on test data achieved is ~0.888. Reuse the same model with 2 Ngram option. What do you have to change? What accuracy do you achieve on test data? Is it better or worse than 1 Ngram?

## Question 2:

#### Find the funtion to retrieve the created vocabulary ( reference: https://www.tensorflow.org/api_docs/python/tf/keras/layers/TextVectorization). Retrieve vocabulary for 2 Ngram model and display and count how many times you see a phrase that contains word 'terrible'.  

## Question 3:

#### In the last part with MultiHeadAttention layer what regularization method could we use to reduce training when performance starts oscilating on the validation set?

## Question 4 optional:

#### In the last part it would be interesting to access and inspect Embedding and MultiHeadAttention layers to understand their structure. But the IMDB dataset is very complex. How can we create a very simple two or four sentences dataset to work with the model and how to access those layers to inspect their weights? The most important thing is that we understand why we are choosing one or the other architecture.     

## Download IMDB data from github and unpack it

In [1]:
!wget https://github.com/erinijapranckeviciene/MF54609_18981_1_20241/raw/refs/heads/main/datasets/RNN/aclImdb.zip

--2025-12-02 10:56:25--  https://github.com/erinijapranckeviciene/MF54609_18981_1_20241/raw/refs/heads/main/datasets/RNN/aclImdb.zip
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erinijapranckeviciene/MF54609_18981_1_20241/refs/heads/main/datasets/RNN/aclImdb.zip [following]
--2025-12-02 10:56:26--  https://raw.githubusercontent.com/erinijapranckeviciene/MF54609_18981_1_20241/refs/heads/main/datasets/RNN/aclImdb.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73380778 (70M) [application/zip]
Saving to: ‘aclImdb.zip’

aclImdb.zip         100%[===================>]  69.98M   296MB/s    in 0.

In [3]:
!unzip -qq aclImdb.zip

## Prepare IMDB data

In [4]:
import os, pathlib, shutil, random
from tensorflow import keras

batch_size = 32
train_ds = keras.utils.text_dataset_from_directory("aclImdb/train", batch_size=batch_size )
val_ds = keras.utils.text_dataset_from_directory("aclImdb/val", batch_size=batch_size)
test_ds = keras.utils.text_dataset_from_directory("aclImdb/test", batch_size=batch_size)

Found 20000 files belonging to 2 classes.
Found 5000 files belonging to 2 classes.
Found 25000 files belonging to 2 classes.


#### Inspect the dataset read from directory files
Displaying the shapes and dtypes of the first batch

In [5]:
for inputs, targets in train_ds:
    print("inputs.shape:", inputs.shape)
    print("inputs.dtype:", inputs.dtype)
    print("targets.shape:", targets.shape)
    print("targets.dtype:", targets.dtype)
    print("inputs[0]:", inputs[0])
    print("targets[0]:", targets[0])
    break

inputs.shape: (32,)
inputs.dtype: <dtype: 'string'>
targets.shape: (32,)
targets.dtype: <dtype: 'int32'>
inputs[0]: tf.Tensor(b"Thoughtless, ignorant, ill-conceived, career-killing (where is the talented Angela Jones now?), deeply unfunny garbage. It's no wonder Reb Braddock hasn't directed anything else since - anyone who has a chance to make his first film on his own rules, based on his own script, with the help of Quentin Tarantino himself, and creates something like THIS, anyone who feels that THIS was a story worth telling to the world, doesn't deserve a second break. Under the circumstances, the performances are good - the actors do what they're told to do, and they do it well. It's just that they shouldn't have done it in the first place. <br /><br />0 out of 4.", shape=(), dtype=string)
targets[0]: tf.Tensor(0, shape=(), dtype=int32)


#### Keep only text in text_only_train_ds. Use only text data.

In [6]:
# This function returns only data part without target
# to create a new dataset that will be used to create dictionary
text_only_train_ds = train_ds.map(lambda x, y: x)
for inputs in text_only_train_ds:
    print("inputs.shape:", inputs.shape)
    print("inputs.dtype:", inputs.dtype)
    print("inputs[0]:", inputs[0])
    break


inputs.shape: (32,)
inputs.dtype: <dtype: 'string'>
inputs[0]: tf.Tensor(b'The Last Hunt is the forgotten Hollywood classic western. The theme of genocide via buffalo slaughter is present in other films but never so savagely. Robert Taylor\'s against-type role as the possessed buffalo and Indian killer is his finest performance.<br /><br />In the 1950s, your mom dropped you and your friends off at the Saterday matin\xc3\xa9e, usually featuring a western or comedy. But it was wrong then and now to let a youngster watch psycho-dramas like The Searchers and The Last Hunt. Let the kids wait a few years before exposing them to films with repressed sexual sadism and intense racial hatred.<br /><br />Why did Mom fail to censor these films? Because they featured "safe" Hollywood stars like Taylor and John Wayne. But the climatic scene in The Last Hunt is as horrifying as Vincent Price\'s mutation in The Fly.<br /><br />The mythology of the white buffalo, part of the texture of this movie, was 

In [7]:
from tensorflow.keras.layers import TextVectorization

# Text vectorization layer creates a structure that will populate with textual data
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/TextVectorization
# This layer performs text standardization, splitting it into Ngrams - single or pairs of words
# It prepares output according to output mode
text_vectorization = TextVectorization( max_tokens=20000, output_mode="multi_hot")

# Use text_only_train_ds to create a dictionary of words that are in IMDB reviews,
# the vocabulary is limited by 20000 (adapt() method)
text_vectorization.adapt(text_only_train_ds)

# Here datasets are created where the text in the string is converted
# to the representation of 20000 dimensional vectors in which a presence of word in
# the text is marked by 1 and absence by 0. This is done for train, validation and test.
binary_1gram_train_ds = train_ds.map( lambda x, y: (text_vectorization(x), y), num_parallel_calls=4)
binary_1gram_val_ds = val_ds.map( lambda x, y: (text_vectorization(x), y),num_parallel_calls=4)
binary_1gram_test_ds = test_ds.map( lambda x, y: (text_vectorization(x), y), num_parallel_calls=4)


In [8]:
for inputs, targets in binary_1gram_train_ds:
    print("inputs.shape:", inputs.shape)
    print("inputs.dtype:", inputs.dtype)
    print("targets.shape:", targets.shape)
    print("targets.dtype:", targets.dtype)
    print("inputs[0]:", inputs[0])
    print("targets[0]:", targets[0])
    break

inputs.shape: (32, 20000)
inputs.dtype: <dtype: 'int64'>
targets.shape: (32,)
targets.dtype: <dtype: 'int32'>
inputs[0]: tf.Tensor([1 1 1 ... 0 0 0], shape=(20000,), dtype=int64)
targets[0]: tf.Tensor(1, shape=(), dtype=int32)


#### This is function creates model from Listing 11.5
Our model-building utility

In [9]:
from tensorflow import keras
from tensorflow.keras import layers

# This is dense model
def get_model(max_tokens=20000, hidden_dim=16):
    inputs = keras.Input(shape=(max_tokens,))
    x = layers.Dense(hidden_dim, activation="relu")(inputs)
    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)
    model = keras.Model(inputs, outputs)
    model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])
    return model

In [10]:
model = get_model()
model.summary()



Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 20000)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 16)             │       320,016 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 320,033 (1.22 MB)

 Trainable params: 320,033 (1.22 MB)

 Non-trainable params: 0 (0.00 B)

#### Training model

In [11]:
# cache() is a dataset method that saves the dataset elements in memory or disk and reuses them when called
callbacks = [ keras.callbacks.ModelCheckpoint("binary_1gram.keras", save_best_only=True) ]
model.fit(binary_1gram_train_ds.cache(), validation_data=binary_1gram_val_ds.cache(), verbose=0, epochs=10, callbacks=callbacks)

In [12]:
# Accuracy on test data
model = keras.models.load_model("binary_1gram.keras")
print(f"Test acc: {model.evaluate(binary_1gram_test_ds)[1]:.3f}")

782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8858 - loss: 0.2923
Test acc: 0.887


## Different output mode -  integer sequence datasets

#### LSTM layer with 4 units gives worse that 2 Ngram

In [13]:
import tensorflow as tf
from tensorflow.keras import layers

# max_length is a length of the vector that encodes text
# 250 size gave ~0.85 on test data
# 600 with 4 LSTM units does not train at all
# the reviews are about 300 words
max_length = 300
max_tokens = 20000
text_vectorization = layers.TextVectorization( max_tokens=max_tokens, output_mode="int", output_sequence_length=max_length)

text_vectorization.adapt(text_only_train_ds)

int_train_ds = train_ds.map(lambda x, y: (text_vectorization(x), y), num_parallel_calls=4)
int_val_ds = val_ds.map(lambda x, y: (text_vectorization(x), y), num_parallel_calls=4)
int_test_ds = test_ds.map(lambda x, y: (text_vectorization(x), y), num_parallel_calls=4)

In [14]:
for inputs, targets in int_train_ds:
    print(inputs.shape)
    print(inputs[0])
    print(targets[0])
    # With this test_input variable verify tf.one_hot() transformation
    test_input=inputs[0]
    break

(32, 300)
tf.Tensor(
[   10   374   309    11   148   580    53     9    87   367    46     3
    10    14     1    33  2154 16943   237     3     2    18    14   180
    50    79    16   249   788  1067     4   110   100    73    61     8
     2     1   135    11    18    76    26     4   313  1330    16    23
    22   100   617   647   162     3  2154  5383   392     1    40  1001
    93   141    11  2836     1    13    10   256   393     2  9452   109
  1534    70     5   168   683  2351  5784   196   122   608     3   106
    82    94    99   187     4  5789    37    11    18    21    86     6
  9869     2  7913     5  4658   200   107   353     3  1833    43   615
    13     1     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0

#### Try RNN for text classification using integer feature vector

In [15]:
tf.one_hot(test_input, depth=max_tokens)

<tf.Tensor: shape=(300, 20000), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [16]:
# The sizes of layers are minimized in order to run
import tensorflow as tf

inputs = keras.Input(shape=(None,), dtype="int64")
# Here will be binary input as test_input

embedded = tf.keras.ops.one_hot(inputs, num_classes=max_tokens)
print(embedded)

# RNN layer
# NOT USE TOO BIG MODEL : x = layers.Bidirectional(layers.LSTM(32))(embedded)
# When units=4 the model runs.
x = layers.LSTM(10)(embedded)
x = layers.Dropout(0.1)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)

model = keras.Model(inputs, outputs)
model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])
model.summary()


<KerasTensor shape=(None, None, 20000), dtype=float32, sparse=False, ragged=False, name=keras_tensor_11>


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, None)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ one_hot (OneHot)                │ (None, None, 20000)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 10)             │       800,440 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 800,451 (3.05 MB)

 Trainable params: 800,451 (3.05 MB)

 Non-trainable params: 0 (0.00 B)

In [17]:
callbacks = [ keras.callbacks.ModelCheckpoint("int_lstm.keras", save_best_only=True) ]

In [18]:
model.fit(int_train_ds, validation_data=int_val_ds, epochs=10, verbose=1, callbacks=callbacks)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 43s 64ms/step - accuracy: 0.5121 - loss: 0.6929 - val_accuracy: 0.5168 - val_loss: 0.6932
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 39s 63ms/step - accuracy: 0.5344 - loss: 0.6869 - val_accuracy: 0.6746 - val_loss: 0.6166
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 65ms/step - accuracy: 0.7110 - loss: 0.5930 - val_accuracy: 0.7996 - val_loss: 0.4969
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 39s 63ms/step - accuracy: 0.7807 - loss: 0.5289 - val_accuracy: 0.8314 - val_loss: 0.4478
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 39s 63ms/step - accuracy: 0.8167 - loss: 0.4745 - val_accuracy: 0.8280 - val_loss: 0.4469
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 40s 63ms/step - accuracy: 0.8521 - loss: 0.4139 - val_accuracy: 0.8510 - val_loss: 0.4071
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 39s 63ms/step - accuracy: 0.8631 - loss: 0.3854 - val_accuracy: 0.8540 - val_loss: 0.4024
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 39s 63ms/step - accuracy: 0.8729 - loss: 0.3379 - 

In [19]:
model = keras.models.load_model("int_lstm.keras")
print(f"Test acc: {model.evaluate(int_test_ds)[1]:.3f}")

782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 25ms/step - accuracy: 0.8476 - loss: 0.3689
Test acc: 0.850


In [20]:
pred=model.predict(int_test_ds)

782/782 ━━━━━━━━━━━━━━━━━━━━ 18s 23ms/step


In [21]:
print(pred)

[[0.8411463 ]
 [0.13959454]
 [0.06240888]
 ...
 [0.06868923]
 [0.06269916]
 [0.06133693]]


In [23]:
import numpy as np

predicted=np.array([int(x>0.5) for x in np.concatenate(pred) ] )
print(predicted)
unique, counts = np.unique(predicted, return_counts=True)
print([unique, counts])

[1 0 0 ... 0 0 0]
[array([0, 1]), array([11986, 13014])]


In [24]:
import numpy as np
# This displays the contents of the dataset
# list(int_test_ds)
# Collect targets to use in confusion table
target_arr=[]
for inputs, targets in int_test_ds:
    target=[int(x) for x in targets]
    target_arr.append(target)

actual=np.concatenate(target_arr)
print(actual)
unique, counts = np.unique(actual, return_counts=True)
print([unique, counts])

[0 0 1 ... 0 1 1]
[array([0, 1]), array([12500, 12500])]


In [25]:
# show confusion table
# Why confusion table shows different accuracy than accuracy of model evaluate?
# Need to investigate, but leaving it for later now.
tf.math.confusion_matrix(actual, predicted)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6052, 6448],
       [5934, 6566]], dtype=int32)>

#### Try to use Enbedding layer for the previous problem

In [27]:
vocab_size = 20000
embed_dim = 256

# ignore from FC book Ch.11 Listing 11.22
#num_heads = 2
#dense_dim = 32

inputs = keras.Input(shape=(None,), dtype="int64")
x = layers.Embedding(vocab_size, embed_dim)(inputs)

x = layers.LSTM(35)(x)

x = layers.Dropout(0.5)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)

# Maybe optimizer could be different?
model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, None)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_1 (Embedding)         │ (None, None, 256)      │     5,120,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 35)             │        40,880 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 35)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,160,916 (19.69 MB)

 Trainable params: 5,160,916 (19.69 MB)

 Non-trainable params: 0 (0.00 B)

In [28]:
callbacks = [ keras.callbacks.ModelCheckpoint("int_embed_lstm.keras", save_best_only=True) ]
model.fit(int_train_ds, validation_data=int_val_ds, epochs=10, verbose=1, callbacks=callbacks)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 15s 21ms/step - accuracy: 0.5025 - loss: 0.6952 - val_accuracy: 0.5100 - val_loss: 0.6937
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 12s 19ms/step - accuracy: 0.5189 - loss: 0.6922 - val_accuracy: 0.5134 - val_loss: 0.6943
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 11s 18ms/step - accuracy: 0.5277 - loss: 0.6891 - val_accuracy: 0.5170 - val_loss: 0.6951
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 21s 19ms/step - accuracy: 0.5345 - loss: 0.6836 - val_accuracy: 0.5406 - val_loss: 0.6770
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 12s 19ms/step - accuracy: 0.5642 - loss: 0.6646 - val_accuracy: 0.5552 - val_loss: 0.6692
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 13s 20ms/step - accuracy: 0.5629 - loss: 0.6502 - val_accuracy: 0.6922 - val_loss: 0.6103
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 12s 19ms/step - accuracy: 0.7228 - loss: 0.5669 - val_accuracy: 0.7758 - val_loss: 0.5720
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 12s 19ms/step - accuracy: 0.7838 - loss: 0.5157 - 

In [29]:
model = keras.models.load_model("int_embed_lstm.keras")
print(f"Test acc: {model.evaluate(int_test_ds)[1]:.3f}")

782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7863 - loss: 0.5370
Test acc: 0.786


### The more complex architecture the poorer results are

#### Model that uses Encoder and MultiHeadAttention layers ( by some analogy to Listing 11.22 )

In [30]:
# What can we do to improve? Here we dont have any RNN, just transformations

vocab_size = 20000
embed_dim = 256

# from FC book Ch.11 Listing 11.22
# num_heads = 2 - acheved 8.69
# Lets try more heads/words
# With 4 heads 8.73 , just a bit , with 5 heads 8.70
# Still worse than a simpler method.
num_heads = 5
dense_dim = 32

inputs = keras.Input(shape=(None,), dtype="int64")
x = layers.Embedding(vocab_size, embed_dim)(inputs)

# try to add attention
x = layers.MultiHeadAttention( num_heads=num_heads, key_dim=embed_dim)(x,x)

# This layer is needed - what it does?
x = layers.GlobalMaxPooling1D()(x)

x = layers.Dropout(0.5)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)

model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_4       │ (None, None)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_2         │ (None, None, 256) │  5,120,000 │ input_layer_4[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, None, 256) │  1,314,816 │ embedding_2[0][0… │
│ (MultiHeadAttentio… │                   │            │ embedding_2[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 256)       │          0 │ multi_head_atten… │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_5 (Dropout) │ (None, 256)       │          0 │ global_max_pooli… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 1)         │        257 │ dropout_5[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 6,435,073 (24.55 MB)

 Trainable params: 6,435,073 (24.55 MB)

 Non-trainable params: 0 (0.00 B)

#### Use model with attention , it really improved from previous, but not compared to more simple model of 2 Ngram.  

In [31]:
callbacks = [ keras.callbacks.ModelCheckpoint("attention.keras", save_best_only=True) ]
model.fit(int_train_ds, validation_data=int_val_ds, epochs=20, callbacks=callbacks)

Epoch 1/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 52s 72ms/step - accuracy: 0.5002 - loss: 0.6947 - val_accuracy: 0.5000 - val_loss: 0.6929
Epoch 2/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 73s 67ms/step - accuracy: 0.5246 - loss: 0.6909 - val_accuracy: 0.6854 - val_loss: 0.6107
Epoch 3/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.6808 - loss: 0.6006 - val_accuracy: 0.7396 - val_loss: 0.4985
Epoch 4/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.7840 - loss: 0.4561 - val_accuracy: 0.8318 - val_loss: 0.3768
Epoch 5/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.8278 - loss: 0.3902 - val_accuracy: 0.8518 - val_loss: 0.3466
Epoch 6/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.8468 - loss: 0.3452 - val_accuracy: 0.8274 - val_loss: 0.3735
Epoch 7/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.8607 - loss: 0.3251 - val_accuracy: 0.8722 - val_loss: 0.3095
Epoch 8/20
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 66ms/step - accuracy: 0.8705 - loss: 0.3079 - 

In [32]:
model = keras.models.load_model("attention.keras")
print(f"Test acc: {model.evaluate(int_test_ds)[1]:.3f}")

782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 15ms/step - accuracy: 0.8655 - loss: 0.3148
Test acc: 0.865
